---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - image: rmccabe3701/inventory-web-app:0.0.1
        name: webapp
        imagePullPolicy: Always
        args: ["-t"]
        env:
        - name: XYZ_MARKETPLACE_VERSION
          value: "0.0.1"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: webapp
  name: webapp
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: webapp
  type: NodePort
